---
  - hosts: authman
    become: true

    tasks:
      - name: update package list
        apt:
          update_cache: yes
        tags:
          - system_update

      - name: upgrade system
        apt:
          upgrade: yes
        tags:
          - system_update

      - name: install docker requirements
        apt:
          name: "{{ item }}"
        with_items:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg-agent
          - software-properties-common
        tags:
          - docker
          - firsttime

      - name: add docker repository key
        apt_key:
          url: https://download.docker.com/linux/ubuntu/gpg
          state: present
        tags:
          - docker
          - firsttime

      - name: adding docker repository
        apt_repository:
          repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable
          state: present
        tags:
          - docker
          - firsttime

      - name: update package list
        apt:
          update_cache: yes
        tags:
          - docker
          - firsttime

      - name: install docker
        apt:
          name: "{{ item }}"
        with_items:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        tags:
          - docker
          - firsttime

      - name: download docker-compose
        shell: "curl -L 'https://github.com/docker/compose/releases/download/1.27.4/docker-compose-$(uname -s)-$(uname -m)' -o /usr/local/bin/docker-compose"
        tags:
          - docker
          - firsttime

      - name: chmod docker-compose
        shell: "chmod +x /usr/local/bin/docker-compose"
        tags:
          - docker
          - firsttime

      - name: clone git repository
        git:
          repo: https://github.com/ssbostan/authman.git
          dest: /opt/authman
        tags:
          - upgrade
          - pull
          - git
          - redeploy
          - deploy

      - name: start application
        docker_compose:
          project_src: /opt/authman
        tags:
          - deploy
